name: EpiSign CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: macos-15

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_16.1.app

      - name: Build GGWave Local Package
        run: swift build -v
        working-directory: Packages/GGWave

      - name: List Available Schemes and Simulators
        run: xcodebuild -list

      - name: Build and Run Tests
        run: |
          xcodebuild test \
            -scheme EpiSign \
            -project EpiSign.xcodeproj \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.1' \
            -derivedDataPath Build/ \
            CODE_SIGNING_ALLOWED=NO \
            COMPILER_INDEX_STORE_ENABLE=NO
        env:
          NSUnbufferedIO: YES

      - name: Upload Test Results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: Build/Logs/Test/*.xcresult